name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.14.1
  - ipython=8.6.0
  - notebook=6.5.2
  - jupyterlab=3.5.0
  - cookiecutter=2.1.1
  - hydra-core=1.2.0
  - matplotlib=3.6.2
  - pandas=1.5.1
  - git=2.30.2
  - pip=22.3.1
  - pip:
      - wandb==0.10.31
