name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=1.2.3
  - pip=20.3.3
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - matplotlib=3.3.4
  - pillow=8.1.2
  - protobuf>=3.0, <3.20
  - pip:
      - wandb==0.10.21
